### ISSUE TITLE
Missing point cloud

### ISSUE THREAD

**Issue by mjdong71** [neumicha/Blender2Helios#8]
Hello, 
I am new to this addon. I tried creating a scene and exporting it into the LiDAR simulator Helios but every time the point cloud created has most of its points missing.
![Screenshot 2022-10-18 135522](https://user-images.githubusercontent.com/116108894/196507825-860ac771-de05-43b7-bd6c-0c175c43919d.png)

**Comment by neumicha** [comment]
Hi @mjdong71 ,
can you please also provide a screenshot (better multiple ones) of the scene in Blender and maybe also of the Helios GUI with the scene loaded?
It's hard to analyze without knowing the exact scene.
Maybe you can also try with an easy scene that only contains a few boxes directly created in Blender.

I am not sure if this is a problem with the addon. My first thought: I am not sure how Helios handles flipped faces/normals. You could check if the normal orientation is somehow related to the bug you are seeing. Have a look at this short video if you are not sure what I mean: https://www.youtube.com/watch?v=jYv4wajsJEY
